myauth/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url
from rest_auth.views import PasswordChangeView
from .forms import RegisterUserForm, ProfileEditForm
from .views import AuthFormsView, LoginView, LogoutView, PasswordResetView, PasswordResetConfirm

urlpatterns = [
    
    url(r'^login/?$', LoginView.as_view(),
        name='login'),
    url(r'^register/?$', AuthFormsView.as_view(form_class=RegisterUserForm),
        name='register-user'),
    url(r'^logout/?$', LogoutView.as_view(),
        name='logout'),
    url(r'^password/change/?$', PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password/reset/?$', PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^profile/?$', AuthFormsView.as_view(form_class=ProfileEditForm),
        name='profile-edit'),
    
]

news/urls.py
from django.conf.urls import url
from .views import ArticlesListView, ArticleDetailView

urlpatterns = [
    url(r'^$', ArticlesListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ArticleDetailView.as_view(), name='detail'),
]

spartak/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

from django.views.generic import TemplateView
from myauth.views import PasswordResetConfirm
admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += [

    #DJANGO ADMIN
    url(r'^admin/', include(admin.site.urls)),

    #IORDER
    url(r'^iorder/', include('iorder.urls', namespace="iorder")),

    #MYAUTH
    url(r'^myauth/', include('myauth.urls', namespace="myauth")),
    url(r'^login/$', TemplateView.as_view(template_name='myauth/pages/login.html'), name="login-page"),
    
    #RESET PASSWORD CONFIRM PAGE
    url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirm.as_view(), name='password_reset_confirm'),

    #BOOKING
    url(r'^booking/', include('booking.urls', namespace="booking")),

    #GALLERY
    url(r'^gallery/', include('gallery.urls', namespace="gallery")),
    
    #PAYMENTS
    url(r'^fail-payment/$', TemplateView.as_view(template_name='myshop/payment/fail.html'), name='payment_fail'),
    url(r'^success-payment/$', TemplateView.as_view(template_name='myshop/payment/success.html'), name='payment_success'),
    url(r'^yandex-money/', include('yandex_money.urls')),
    url(r'^yandex-money/redirect/', include('shop_yandex.urls', namespace="shop-yandex")),

    #FEEDBACK
    url(r'^feedback/', include('feedback.urls', namespace="feedback")),

    #ORDERS-CONTROL
    url(r'^shop/', include('myshop.urls', namespace="shop")),
    #CMS PAGES
    url(r'^', include('cms.urls')),
    #prefix_default_language=False
]

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

myauth/models.py
from django.db import models

# Create your models here.

myauth/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model, authenticate, login
from django.core.exceptions import ValidationError
from django.forms import widgets
from django.shortcuts import render
from django.contrib.sites.shortcuts import get_current_site
from django.template import Context
from django.template.loader import select_template

from djng.forms import fields, NgModelFormMixin, NgFormValidationMixin
from djng.styling.bootstrap3.forms import Bootstrap3ModelForm
from djng.forms.widgets import RadioSelect

from shop.forms.base import UniqueEmailValidationMixin
from myshop.models import Customer

class RegisterUserForm(NgModelFormMixin, NgFormValidationMixin, UniqueEmailValidationMixin, Bootstrap3ModelForm):
    form_name = 'register_user_form'
    scope_prefix = 'form_data'
    field_css_classes = 'input-group has-feedback'

    email = fields.EmailField(label=_("Your e-mail address"))

    preset_password = fields.BooleanField(
        label=_("Preset password"),
        widget=widgets.CheckboxInput(),
        required=False,
        help_text=_("Send a randomly generated password to your e-mail address."))

    password1 = fields.CharField(
        label=_("Choose a password"),
        widget=widgets.PasswordInput,
        min_length=6,
        help_text=_("Minimum length is 6 characters."),
    )

    password2 = fields.CharField(
        label=_("Repeat password"),
        widget=widgets.PasswordInput,
        min_length=6,
        help_text=_("Confirm password."),
    )

    class Meta:
        model = Customer
        fields = ('name', 'surname', 'email', 'phone', 'preset_password', 'password1', 'password2') 

    def __init__(self, data=None, instance=None, *args, **kwargs):
        if data and data.get('preset_password', False):
            pwd_length = max(self.base_fields['password1'].min_length, 8)
            password = get_user_model().objects.make_random_password(pwd_length)
            data['password1'] = data['password2'] = password
        super(RegisterUserForm, self).__init__(data=data, instance=instance, *args, **kwargs)

    def clean(self):
        cleaned_data = super(RegisterUserForm, self).clean()
        # check for matching passwords
        if 'password1' not in self.errors and 'password2' not in self.errors:
            if cleaned_data['password1'] != cleaned_data['password2']:
                msg = _("Passwords do not match")
                raise ValidationError(msg)
        return cleaned_data

    def save(self, request=None, commit=True):
        self.instance.user.is_active = True
        self.instance.user.email = self.cleaned_data['email']
        self.instance.user.set_password(self.cleaned_data['password1'])
        self.instance.recognize_as_registered(request, commit=False)
        customer = super(RegisterUserForm, self).save(commit)
        password = self.cleaned_data['password1']
        self._send_notification(request, customer, password)
        user = authenticate(username=customer.user.username, password=password)
        login(request, user)
        return customer

    def _send_notification(self, request, customer, password):
        user = customer.user
        current_site = get_current_site(request)
        context = Context({
            'site_name': current_site.name,
            'absolute_base_uri': request.build_absolute_uri('/'),
            'email': user.email,
            'password': password,
            'customer': customer,
        })
        subject = "{} {}".format(_("Welcome to"), current_site.name)
        subject = ''.join(subject.splitlines())

        body_txt = select_template(['myauth/email/registration.txt',]).render(context)
        body_html = select_template(['myauth/email/registration.html',]).render(context)

        user.email_user(subject, body_txt, html_message=body_html)

class ProfileEditForm(NgModelFormMixin, NgFormValidationMixin, Bootstrap3ModelForm):
    success_message = _("Profile data saved successfully.")
    form_name = 'profile_edit_form'
    scope_prefix = 'form_data'

    email = fields.EmailField(label=_("Your e-mail address"))

    password1 = fields.CharField(
        required=False,
        label=_("New password"),
        widget=widgets.PasswordInput,
        min_length=6,
        help_text=_("Minimum length is 6 characters."),
    )

    password2 = fields.CharField(
        required=False,
        label=_("Repeat password"),
        widget=widgets.PasswordInput,
        min_length=6,
        help_text=_("Confirm password."),
    )

    class Meta:
        model = Customer
        fields = ('name', 'surname', 'age', 'sex', 'email','phone', 'password1', 'password2')
 
    def __init__(self, data=None, instance=None, *args, **kwargs):
        if not data or not data.get('email', False):
            kwargs.update(initial={
                'email': instance.user.email
            })
        super(ProfileEditForm, self).__init__(data=data, instance=instance, *args, **kwargs)

    def clean_email(self):
        if not self.cleaned_data['email']:
            raise ValidationError(_("Please provide a valid e-mail address"))
        # check for uniqueness of email address
        if self.instance.user.email != self.cleaned_data['email']:
            if Customer.objects.filter(is_active=True, user_email=self.cleaned_data['email']).exists():
                msg = _("A customer with the e-mail address '{email}' already exists.\n"
                        "If you have used this address previously, try to reset the password.")
                raise ValidationError(msg.format(**self.cleaned_data))
        return self.cleaned_data['email']

    def clean(self):
        cleaned_data = super(ProfileEditForm, self).clean()
        # check for matching passwords
        if 'password1' in self.cleaned_data:
            if 'password2' not in self.cleaned_data:
                raise ValidationError(_("Please confirm password"))
            if cleaned_data['password1'] != cleaned_data['password2']:
                msg = _("Passwords do not match")
                raise ValidationError(msg)
        return cleaned_data

    def save(self, request=None, commit=True):
        user = super(ProfileEditForm, self).save(commit)
        if self.cleaned_data['password1']:
            self.instance.user.set_password(self.cleaned_data['password1'])
            if commit:
                user.save()
        return user

myauth/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import TemplateView

from django.contrib.auth import logout
from django.contrib.auth.models import AnonymousUser
from django.utils.translation import ugettext_lazy as _

from django.shortcuts import redirect
from django.template import RequestContext

from rest_framework import status
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response

from shop.views import auth
from myshop.models import Customer
from .forms import ProfileEditForm

class ProfileEditView(TemplateView):
    template_name = "myauth/pages/profile.html"
    def get_context_data(self, **kwargs):
        context = super(ProfileEditView, self).get_context_data(**kwargs)
        customer = self.request.customer
        context['profile_edit_form'] = ProfileEditForm(instance=customer)
        return context

class AuthFormsView(GenericAPIView):
    serializer_class = None
    form_class = None

    def post(self, request, *args, **kwargs):

        if request.customer.is_visitor():
            customer = Customer.objects.get_or_create_from_request(request)
        else:
            customer = request.customer

        form = self.form_class(data=request.data, instance=customer)

        if form.is_valid():
            form.save(request=request)
            try:
                msg = form.success_message
            except AttributeError:
                msg = None
            return Response({'success': msg}, status=status.HTTP_200_OK)

        return Response(dict(form.errors), status=status.HTTP_400_BAD_REQUEST)

class LoginView(auth.LoginView):
    pass

class LogoutView(auth.LogoutView):
    
    def get(self, request):
        try:
            request.user.auth_token.delete()
        except:
            pass
        logout(request)
        request.user = AnonymousUser()
        #request.META['HTTP_REFERER']
        return redirect('/')

from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_text

from rest_framework.permissions import AllowAny
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer, BrowsableAPIRenderer
from rest_framework.response import Response

from shop.models.customer import CustomerModel
from .serializers import PasswordResetSerializer, PasswordResetConfirmSerializer


class PasswordResetView(GenericAPIView):
    """
    Calls Django Auth PasswordResetForm save method.

    Accepts the following POST parameters: email
    Returns the success/fail message.
    """
    serializer_class = PasswordResetSerializer
    permission_classes = (AllowAny,)

    def post(self, request, *args, **kwargs):
        # Create a serializer with request.data
        serializer = self.get_serializer(data=request.data)
        if not serializer.is_valid():
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        serializer.save()
        # Return the success message with OK HTTP status
        msg = _("Instructions on how to reset the password have been sent to '{email}'.")
        return Response(
            {'success': msg.format(**serializer.data)},
            status=status.HTTP_200_OK
        )

class PasswordResetConfirm(GenericAPIView):
    """
    Password reset e-mail link points onto this view, which when invoked by a GET request renderes
    a HTML page containing a password reset form. This form then can be used to reset the user's
    password using a RESTful POST request.

    Since the URL for this view is part in the email's body text, expose it to the URL patterns as:

    ```
    url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    ```

    Accepts the following POST parameters: new_password1, new_password2
    Returns the success/fail message.
    """
    renderer_classes = (TemplateHTMLRenderer, JSONRenderer, BrowsableAPIRenderer)
    serializer_class = PasswordResetConfirmSerializer
    permission_classes = (AllowAny,)
    template_name = 'myauth/pages/password-reset.html'
    token_generator = default_token_generator

    def get(self, request, uidb64=None, token=None):
        data = {'uid': uidb64, 'token': token}
        serializer_class = self.get_serializer_class()
        password = get_user_model().objects.make_random_password()
        data.update(new_password1=password, new_password2=password)
        serializer = serializer_class(data=data, context=self.get_serializer_context())
        if not serializer.is_valid():
            return Response({'validlink': False})
        return Response({'validlink': True, 'user_name': force_text(serializer.user)})

    def post(self, request, uidb64=None, token=None):
        data = dict(request.data, uid=uidb64, token=token)
        serializer = self.get_serializer(data=data)
        if not serializer.is_valid():
            return Response(
                serializer.errors, status=status.HTTP_400_BAD_REQUEST
            )
        serializer.save()
        return Response({"success": _("Password has been reset with the new password.")})

myauth/templates/myauth/forms/base.html
<my-auth-form ng-form name="{% block form_name %}{% endblock %}" 
              form-submit-url="{% block submit_url %}{% endblock %}"
              action="{{ action }}" 
              role="form" 
              class="form form-style" >
    {% csrf_token %}
    {% block form_content %}
    <div class="alert alert-success" ng-show="success_message" ng-cloak>{% verbatim %}{{ success_message }}{% endverbatim %}
    </div>
    <div class="alert alert-danger" ng-show="error_message" ng-cloak>{% verbatim %}{{ error_message }}{% endverbatim %}
    </div>
    {% endblock%}

    {% block form_footer %}
    {% endblock %}
</my-auth-form>

myauth/templates/myauth/forms/password_reset.html
{% extends "myauth/forms/base.html" %}
{% load i18n %}

{% block form_name %}reset_form{% endblock %}

{% block submit_url %}{% url 'myauth:password-reset' %}{% endblock %}
{% block form_content %}
    {{ block.super }}
    <div class="form-group pendant-help-block has-feedback" ng-class="hasError('email')">
            <input type="email" class="form-control" name="email" ng-model="form_data.email" value="" placeholder="Ваша электронная почта" ng-required="true"/>
            <ul ng-messages="reset_form.email.$error" class="shop-form-error" ng-cloak>
                <li ng-show="reset_form.email.$dirty" ng-message="email">Укажите правильный E-Mail</li>
                <li ng-show="reset_form.email.$pristine" ng-message="rejected"><span ng-bind="reset_form.email.$message"></span></li>
            </ul>
    </div>
{% endblock %}

{% block form_footer %}
        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <a role="button" class="btn btn-xs btn-gray btn-block"  
                            ng-click="$parent.setAction('auth')">Вернуться</a>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <a role="button" class="btn btn-xs btn-block btn-second"
                            ng-click="submitForm('{% url 'myauth:password-reset' %}')" 
                            ng-disabled="reset_reset_form.$invalid">Запросить пароль</a>
                </div>
            </div>
        </div>
{% endblock %}

myauth/templates/myauth/forms/profile.html
{% extends "myauth/forms/base.html" %}
{% load i18n %}

{% block form_name %}profile_edit_form{% endblock %}

{% block submit_url %}{% url 'myauth:profile-edit' %}{% endblock %}
{% block form_content %}
    {{ block.super }}
    <h4>Расскажите о себе</h4>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group pendant-help-block has-feedback" ng-class="hasError('name')">
                <input type="text" name="name" class="form-control" placeholder="Имя"
                       ng-model="form_data['name']"
                       ng-required="true"
                       ng-init="form_data['name']='{{profile_edit_form.name.value}}'"/>
                <ul ng-messages="profile_edit_form.name.$error" class="shop-form-error" ng-cloak>
                    <li ng-show="profile_edit_form.name.$pristine" ng-message="rejected">
                        <span ng-bind="profile_edit_form.name.$message"></span>
                    </li>
                </ul>
            </div>
            <!-- Внимание!!! Дублирование поля Возраст для хорошего порядка на мобилах!!! -->
            <div class="form-group pendant-help-block hidden-xs">
                <input type="text" ng-model="form_data['age']"  value="{{profile_edit_form.age.value}}" initial-value name="age" class="form-control" placeholder="Возраст"/>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group has-feedback"  g-class="hasError('surname')">
                <input type="text" name="surname" class="form-control" placeholder="Фамилия"
                       ng-model="form_data['surname']"
                       ng-required="true"
                       ng-init="form_data['surname']='{{profile_edit_form.surname.value}}'"/>
                <ul ng-messages="profile_edit_form.surname.$error" class="shop-form-error" ng-cloak>
                    <li ng-show="profile_edit_form.surname.$pristine" ng-message="rejected">
                        <span ng-bind="profile_edit_form.surname.$message"></span>
                    </li>
                </ul>
            </div>
            <!-- Внимание!!! Дублирование поля Возраст для хорошего порядка на мобилах!!! -->
            <div class="form-group pendant-help-block visible-xs">
                <input type="text" ng-model="form_data['age']" value="{{profile_edit_form.age.value}}" initial-value name="age" class="form-control" placeholder="Возраст" />
            </div>
            <div class="form-group pendant-help-block">
                <div class="label">Пол: </div>
                <div class="radio" ng-init="form_data['sex']='{{profile_edit_form.sex.value}}'">
                    <label><input type="radio" name="sex" ng-model="form_data['sex']" value="male">Мужской</label>
                </div>
                <div class="radio">
                    <label><input type="radio" name="sex" ng-model="form_data['sex']" value="female">Женский</label>
                </div>
            </div>
        </div>
    </div>

    <h4>Контактные данные</h4>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group pendant-help-block">
                <input type="text" name="phone" class="form-control" placeholder="Телефон"
                       ng-model="form_data['phone']"
                       ng-required="true"
                       ng-init="form_data['phone']='{{profile_edit_form.phone.value}}'"/>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group has-feedback" ng-class="hasError('email')">                
            <input type="text" name="email" class="form-control" placeholder="E-Mail"
                       ng-model="form_data['email']"
                       ng-required="true"
                       ng-init="form_data['email']='{{profile_edit_form.email.value}}'"/>
                <ul ng-messages="profile_edit_form.email.$error" class="shop-form-error" ng-cloak>
                    <li ng-show="profile_edit_form.email.$dirty" ng-message="email">Укажите правильный E-Mail</li>
                    <li ng-show="profile_edit_form.email.$pristine" ng-message="rejected"><span ng-bind="profile_edit_form.email.$message"></span></li>

                </ul>
            </div>
        </div>
    </div>
    <h4>Изменить пароль</h4>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group pendant-help-block has-feedback"  ng-class="hasError('password')">
                <div class="input-group" ng-class="hasError('password1')"> 
                    <input type="password" class="form-control" name="password1" ng-minlength="6" ng-required="false" ng-model="form_data['password1']" placeholder="Пароль"/>
                </div>
                <ul ng-messages="profile_edit_form.password1.$error" class="shop-form-error" ng-cloak>
                    <li ng-message="minlength">Пароль слишком короткий</li>
                    <li ng-message="rejected"><span ng-bind="profile_edit_form.password1.$message"></span></li>
                </ul>
                <span class="help-block">Мин. длинна: 6 символов</span>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group pendant-help-block has-feedback"  ng-class="hasError('password2')">
                <div class="input-group" ng-class="hasError('password2')">
                    <input type="password" class="form-control" name="password2"  ng-minlength="6" ng-required="false" ng-model="form_data['password2']" placeholder="Повторите пароль"/>
                </div>
                <ul ng-messages="profile_edit_form.password2.$error" class="shop-form-error" ng-cloak>
                    <li ng-message="minlength">Пароль слишком короткий</li>
                    <li ng-message="rejected"><span ng-bind="profile_edit_form.password2.$message"></span></li>
                </ul>
                <span class="help-block"></span>
            </div>
        </div>
    </div>

{% endblock %}

{% block form_footer %}
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 with-btn">
                <button class="btn btn-lg btn-main" 
                        ng-click="submitForm('{% url 'myauth:profile-edit' %}')" 
                        ng-disabled="profile_edit_form.$invalid">Cохранить</button>
        </div>
    </div>
{% endblock %}

myauth/templates/myauth/forms/signin.html
{% extends "myauth/forms/base.html" %}
{% load i18n %}

{% block form_name %}auth_form{% endblock %}
{% block submit_url %}{% url 'myauth:login' %}{% endblock %}
{% block form_content %}
    {{ block.super }}
    <div class="form-group pendant-help-block has-feedback" ng-class="hasError('username')">
        <input type="text" class="form-control" name="username" 
                   ng-model="form_data.username" value="" 
                   placeholder="Электронная почта" ng-required="true"/>
        <ul ng-messages="auth_form.username.$error" class="shop-form-error" ng-cloak>
            <li ng-message="rejected"><span ng-bind="auth_form.username.$message"></span></li>
        </ul>
    </div>

    <div class="form-group pendant-help-block" ng-class="hasError('password')">  
        <input type="password" class="form-control" 
                   name="password" ng-model="form_data.password" 
                   placeholder="Пароль" ng-required="true"/>
        <ul ng-messages="auth_form.password.$error" class="shop-form-error" ng-cloak>
            <li ng-message="rejected"><span ng-bind="auth_form.password.$message"></span></li>
        </ul>
    </div>


    <div class="form-group">
        <div class="checkbox">
            
        </div>
        <p class="small"></p>
    </div>
{% endblock %}

{% block form_footer %}
    <div class="form-group">
        <div class="col-sm-6 col-sm-offset-3 ">
            <a role="button" class="btn btn-sm btn-block btn-second"
                    ng-click="submitForm('{% url 'myauth:login' %}', 0)"
                    ng-disabled="auth_form.$invalid">Войти</a>
        </div>
    </div>
{% endblock %}

myauth/templates/myauth/forms/signup.html
{% extends "myauth/forms/base.html" %}
{% load i18n %}

{% block form_name %}register_user_form{% endblock %}
{% block submit_url %}{% url 'myauth:register-user' %}{% endblock %}
{% block form_content %}
    {{ block.super }}
    <div class="form-group pendant-help-block has-feedback" ng-class="hasError('name')">
        <input type="text" class="form-control" name="name" ng-model="form_data['name']" placeholder="Ваше имя"  ng-required="true"/>
        <ul ng-messages="register_user_form.name.$error" class="shop-form-error" ng-cloak>
            <li ng-show="register_user_form.name.$pristine" ng-message="rejected">
                <span ng-bind="register_user_form.name.$message"></span>
            </li>
        </ul>
    </div>

    <div class="form-group has-feedback"  g-class="hasError('surname')">
        <input type="text" class="form-control" name="surname" ng-model="form_data['surname']" placeholder="Ваша фамилия" ng-required="true"/>
        <ul ng-messages="register_user_form.surname.$error" class="shop-form-error" ng-cloak>
            <li ng-show="register_user_form.surname.$pristine" ng-message="rejected">
                <span ng-bind="register_user_form.surname.$message"></span>
            </li>
        </ul>
    </div>

    <div class="form-group pendant-help-block ">
        <input type="text" class="form-control" name="phone" ng-model="form_data['phone']" placeholder="Телефон"/>
    </div>

    <div class="form-group has-feedback" ng-class="hasError('email')">
        <input type="email" class="form-control" name="email" ng-model="form_data['email']" placeholder="Электронная почта" ng-required="true"/>
        <ul ng-messages="register_user_form.email.$error" class="shop-form-error" ng-cloak>
            <li ng-show="register_user_form.email.$dirty" ng-message="email">Укажите правильный E-Mail</li>
            <li ng-show="register_user_form.email.$pristine" ng-message="rejected"><span ng-bind="register_user_form.email.$message"></span></li>
        </ul>
    </div>
    <div class="form-group">
        <div class="checkbox">
            <label><input name="preset_password" ng-init="form_data['preset_password']=true" ng-model="form_data['preset_password']" type="checkbox">Предустановленный пароль</label>
        </div>
        <p class="small">На ваш емейл будет выслан сгенерированный пароль.</p>
    </div>
    <div ng-if="!form_data.preset_password">
        <div class="form-group pendant-help-block has-feedback"  ng-class="hasError('password')">
            <div class="input-group" ng-class="hasError('password1')"> 
                <input type="password" class="form-control" name="password1" ng-minlength="6" ng-required="true" ng-model="form_data['password1']" placeholder="Пароль" ng-required="true"/>
            </div>
            <ul ng-messages="register_user_form.password1.$error" class="shop-form-error" ng-cloak>
                <li ng-message="minlength">Пароль слишком короткий</li>
                <li ng-message="rejected"><span ng-bind="register_user_form.password1.$message"></span></li>
            </ul>
            <span class="help-block">Мин. длинна: 6 символов</span>
        </div>
        <div class="form-group pendant-help-block has-feedback"  ng-class="hasError('password2')">
            <div class="input-group" ng-class="hasError('password2')">
                <input type="password" class="form-control" name="password2"  ng-minlength="6" ng-required="true" ng-model="form_data['password2']" placeholder="Повсторите пароль" ng-required="true"/>
            </div>
            <ul ng-messages="register_user_form.password2.$error" class="shop-form-error" ng-cloak>
                <li ng-message="minlength">Пароль слишком короткий</li>
                <li ng-message="rejected"><span ng-bind="register_user_form.password2.$message"></span></li>
            </ul>
            <span class="help-block"></span>
        </div>
    </div>
{% endblock %}

{% block form_footer %}
    <div class="form-group">
        <div class="row">
            <div class="col-xs-12 col-sm-12 text-center">
                <a role="button" class="btn btn-xs btn-second btn-block" 
                        ng-click="submitForm('{% url 'myauth:register-user' %}')" 
                        ng-disabled="register_user_form.$invalid">Зарегистрироваться</a>
            </div>
        </div>
    </div>
{% endblock %}